pesan/urls.py
from django.urls import path 
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index , name='story7-home'),
    path('konfirmasipesan/', views.konfirmasi_pesan, name='story7-confirm'),
    path('ubahwarna/<int:postid>/', views.ubah_warna),
]

story7/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pesan.urls')),
]

pesan/models.py
from django.db import models

# Create your models here.
class Warna(models.Model):
    kode_warna = models.CharField(max_length = 16, unique=True)

class Pesan(models.Model):
    nama = models.CharField(max_length=32)
    pesan = models.TextField()
    tanggal_dibuat = models.DateTimeField(auto_now=True)
    warna = models.ForeignKey(Warna, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.nama + ' - ' + self.pesan

pesan/views.py
from django.shortcuts import render, redirect
from .models import Pesan , Warna

# Create your views here.
def index(request, sign = ''):
    if request.method == 'POST':
        if request.POST['isi'] == '':
            sign = 'failed'
        else:
            Pesan.objects.create(
            nama = request.POST.get('nama'),
            pesan = request.POST.get('isi')
            )
            sign = 'success'
    status = Pesan.objects.all()
    return render(request, 'index.html',{'status' : status , 'sign' : sign})

def konfirmasi_pesan(request):
    if request.method == 'POST':
        if request.POST['nama'] != '':
            nama = request.POST['nama']
        else :
            nama = 'Anonymous'
        context = {
            'nama':nama,
            'pesan':request.POST['isi'],
        }
        return render(request,'konfirmasipesan.html', context)
    return redirect('/')

def ubah_warna(request, postid):
    try:
        pesan = Pesan.objects.get(id=postid)
        try: 
            id_warna_sekarang = pesan.warna.id
        except:
            id_warna_sekarang = 0
        
        id_warna_terakhir = Warna.objects.latest('id').id
        if id_warna_sekarang+1 > id_warna_terakhir:
            warna = Warna.objects.all().first()
        else:
            warna = Warna.objects.filter(id__gt=id_warna_sekarang).order_by('id').first()
        pesan.warna = warna
        pesan.save()
    except Pesan.DoesNotExist:
        pass
    return redirect('/')

pesan/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'Letter-S.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
    <footer id="footer">
        <div class="container">
            <div class="copyright">
                Copyright &copy;<strong><span> Suwandi</span></strong> 2020
            </div>
            <div class="credits">
                FASILKOM UI
            </div>
        </div>
    </footer>
    <a href="#" class="ignielToTop" id="myBtn"></a>
    <script>
        var mybutton = document.getElementById("myBtn");
        window.onscroll = function() {scrollFunction()};
        function scrollFunction() {
            if (document.body.scrollTop > 30 || document.documentElement.scrollTop > 30) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }
    </script>
</body>
</html>

pesan/templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Curhatin AJA {% endblock %}
{% block content %}
<main id="main">
    <div class="d-flex flex-row flex-wrap">
        <div id="box1">
            <p style="text-align: center;font-size: large;margin-top: 10px;"><b>Curhatin AJA</b></p>
        </div>
        <div class="container mt-2" style="background: aqua; margin-left:0px;">
            <h4>Curhat? & Butuh temen?<span style="color:#ffba00"> disini aja</span></h4>
        </div>
        <div class="container">
            {% if sign %}
                {% if sign == 'success' %}
                <div class="alert alert-success" role="alert" style="max-width: 70%">
                    Sukses menambahkan status ! , sekarang semua orang dapat melihat statusmu.
                </div>
                {% else %}
                <div class="alert alert-danger" role="alert" style="max-width: 70%">
                    Mohon lengkapi kolom pesan dan silahkan coba lagi !
                </div>
                {% endif %}
            {% endif %}
            <!-- Bagian tambah pesan -->
            <h2 class="tambah-pesan">Tambahkan <span style="color:#ffba00">Pesan/Status</span> Anda Disini</h2>
            <h5 class="notes">Notes : Jika nama dikosongi maka akan tertulis Anonymous</h5>
            <form class="ulasan-form d-flex flex-column" method="POST" action="{% url 'story7:story7-confirm' %}">
                {% csrf_token %}
                <input type="text" class="pesan-input" name="nama" id="nama" placeholder='Masukkan nama anda (boleh kosong)'>
                <textarea type="text" class="pesan-input" name="isi" id="isi" placeholder='Tuliskan pesan/status yang ingin anda ungkapkan'></textarea>
                <button type="submit" id="submit" class=" button-ulasan buyNowBtn btn btn-warning">Add Status</button>
            </form>
        </div>
        <!-- Bagian Pesan -->
        <div class="container" style="border: 1px solid rgba(0, 0, 0, 0.212); box-sizing: border-box; width: 100vw;">
            <h1 class="homepage-pesan">Pesan</h1>
            <div class="d-flex flex-wrap">
            {% for pesan in status %}
                <div class="box-ulasan" name="history-pesan" id="history-pesan" style="background-color: {{pesan.warna.kode_warna}};">
                    <div class="date-block">
                        <p>{{pesan.tanggal_dibuat}}</p>
                    </div>
                    <h4>{{pesan.nama}}</h4>
                    <p>{{pesan.pesan}}</p>
                    <a href="/ubahwarna/{{pesan.id}}">
                        <button class="button" name="change-color" type="submit" id="change-color" style="vertical-align:middle"><span>Change Color</span></button>
                    </a>  
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>    
    <div class="container mt-4 contact-me">
        <div class="icon-bar">
            <p><b>Contact me</b></p>
            <p>
                <a href="https://m.facebook.com/suwandi.kurniawan.904?ref=bookmarks/" class="facebook"><i class="fa fa-facebook"></i></a>  
                <a href="https://www.instagram.com/suwandi_k89/" class="instagram"><i class="fa fa-instagram"></i></a> 
                <a href="https://api.whatsapp.com/send?phone=8197757988&text=Hi,%20Saya%20Suwandi%20Kurniawan,%20senang%20dapat%20berkenalan%20dengan%20kalian..." class="whatsapp"><i class="fa fa-whatsapp"></i></a>
            </p>
            <p>
                <a href="https://drive.google.com/open?id=1E2vl5WJl3gEzOE2OM22ovRtK599Nf8c_" class="google"><i class="fa fa-google"></i></a> 
                <a href="https://www.linkedin.com/in/suwandi-kurniawan-b05827150/" class="linkedin"><i class="fa fa-linkedin"></i></a>
                <a href="https://www.youtube.com/channel/UC6MyCZGwQusU8qUSYRQCb4g/" class="youtube"><i class="fa fa-youtube"></i></a> 
            </p>
        </div>  
    </div> 
</main>
{% endblock %}

pesan/templates/konfirmasipesan.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Curhatin AJA - Confirm {% endblock %}
{% block content %}
<main id="main">
    <div class="d-flex flex-row flex-wrap">
        <div id="box1">
            <p style="text-align: center;font-size: large;margin-top: 10px;"><b>Curhatin AJA</b></p>
        </div>
        <div class="container mt-2" style="background: aqua; margin-left:0px;">
            <h4>Curhat? & Butuh temen?<span style="color:#ffba00"> disini aja</span></h4>
        </div>
        <div class="container">
            <form action="{% url 'story7:story7-home' %}" method="POST" class="ulasan-form d-flex flex-column">
                {% csrf_token %}
                <label for="id_name">Nama: </label>
                <input type="text" name="nama" class="pesan-input" value="{{ nama }}" readonly>
                <label for="id_status">Status: </label>
                <textarea name="isi" class="pesan-input"readonly>{{ pesan }}</textarea>
                <div class="button-group">
                    <a href="/"><button type="button" class="btn btn-secondary">Back</button></a>
                    <input type="hidden" id="confirm" name="action" value="confirm">
                    <input type="submit" id="confirm" class="btn btn-primary" value="Confirm"> 
                </div>
            </form>
        </div>
    </div>
    <div class="container mt-4 contact-me">
        <div class="icon-bar">
            <p><b>Contact me</b></p>
            <p>
                <a href="https://m.facebook.com/suwandi.kurniawan.904?ref=bookmarks/" class="facebook"><i class="fa fa-facebook"></i></a>  
                <a href="https://www.instagram.com/suwandi_k89/" class="instagram"><i class="fa fa-instagram"></i></a> 
                <a href="https://api.whatsapp.com/send?phone=8197757988&text=Hi,%20Saya%20Suwandi%20Kurniawan,%20senang%20dapat%20berkenalan%20dengan%20kalian..." class="whatsapp"><i class="fa fa-whatsapp"></i></a>
            </p>
            <p>
                <a href="https://drive.google.com/open?id=1E2vl5WJl3gEzOE2OM22ovRtK599Nf8c_" class="google"><i class="fa fa-google"></i></a> 
                <a href="https://www.linkedin.com/in/suwandi-kurniawan-b05827150/" class="linkedin"><i class="fa fa-linkedin"></i></a>
                <a href="https://www.youtube.com/channel/UC6MyCZGwQusU8qUSYRQCb4g/" class="youtube"><i class="fa fa-youtube"></i></a> 
            </p>
        </div>  
    </div> 
</main>
{% endblock %}